# Generated by Django 6.0.2 on 2026-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('volunteer', 'Volunteer'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
